### ISSUE TITLE
Move from bash to tiny

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/docker#1]
Use <https://github.com/krallin/tini>, like in c-lightning default docker container, for all shells inside containers

**Comment by dr-orlovsky** [comment]
@zoedberg feel free to grab this task if you'd like to

**Comment by zoedberg** [comment]
usually I use tini only where it's needed (like in most rust applications, to handle stop signals), to avoid adding unnecessary stuff that just increases the final image size. @dr-orlovsky  could you explain your reason to add it on all images? 

anyway, yes, I can take this issue

**Comment by dr-orlovsky** [comment]
I am not that good in the CI, so I had no specific reason than the fact I seen it somewhere. So let's close this issue then :)

**Comment by zoedberg** [comment]
I can verify that all images handle stop signals correctly and add tini where they don't ;)

**Comment by zoedberg** [comment]
> I can verify that all images handle stop signals correctly and add tini where they don't ;)

It seems they all do, so I think this issue can be closed
