### ISSUE TITLE
bitcoind: use rpcauth instead of rpc(user|password)

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/docker#23]
when launching bitcoind this log appears: `Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.` (from [here](https://github.com/bitcoin/bitcoin/blob/0.18/src/httprpc.cpp#L227))

to generate an rpcauth, from the bitcoin repo, run: `./share/rpcauth/rpcauth.py <username> <password>`

for this project, using `bitcoin` as user and password, the rpcauth is: `rpcauth=bitcoin:c15fb70bbb0239f9cfdfc8b5d48d67a2$0c9257124cf65b816e06fb8c657de4c5cc458d3385ca8242ba7ac17b29aeb064`

I propose to change the bitcoind `command` directive in all compose files,  putting instead of `-rpcuser=bitcoin` and `-rpcpassword=bitcoin`, the rpcauth flag (escaping the dollar symbol for `yaml`): `-rpcauth=bitcoin:c15fb70bbb0239f9cfdfc8b5d48d67a2$$0c9257124cf65b816e06fb8c657de4c5cc458d3385ca8242ba7ac17b29aeb064`

**Comment by dr-orlovsky** [comment]
Completely agree. It's already part of our design features and mentioned in issue https://github.com/LNP-BP/docker/issues/20
