### ISSUE TITLE
Add RGB Node docker container

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/docker#8]
From https://github.com/LNP-BP/rgb-node/pull/71

**Comment by zoedberg** [comment]
For some reason I can't grasp, the docker image doesn't build from last tag, `v0.1.0-beta.3` (it gives some compile errors).
But changing the git ref to `master` makes it build successfully. @dr-orlovsky  Can you add a new tag?

**Comment by dr-orlovsky** [comment]
I am going to make a new Beta 4 release early next week; probably it will be nice to wait till then
